change circulating supply of crnchy token
crunchy-network/crunchy-dapp pull request #163
Opened 2024-01-14 03:58 UTC by huydo2105

2024-01-20 05:06 UTC, mycodecrafting requested changes

2024-01-20 05:06 UTC, mycodecrafting commented on src/components/TokenMetrics.vue
> +      console.log(this.getTokenOverview.tokenAddress)
remove

2024-01-20 11:36 UTC, huydo2105 commented on src/components/TokenMetrics.vue
> +      console.log(this.getTokenOverview.tokenAddress)
Resolved

2024-01-22 03:37 UTC, mycodecrafting approved these changes

2024-01-22 03:37 UTC, merged